export const BOOKING_MINUTES_PER_TIMESLOT = 60;
export const BOOKING_CALENDAR_DAYS = 7;
export const BOOKING_CALENDAR_DAY_OPENING_TIME = "0500";
export const BOOKING_CALENDAR_DAY_CLOSING_TIME = "2100";
